### PR TITLE
Move MQTT topics and payload into an extendable dictionary

### PR DESCRIPTION
**Pull request by ndbroadbent**
This change moves all the MQTT topics and payloads into a dictionary, so that additional commands can be configured in the settings JSON file

### CODE REVIEW

**Comment by nicko88** [comment]
Thanks, I’ll check it out. 

I brainstormed how I wanted to handle this extension over the holiday a bit and came up with some ideas. 

This is probably close to the ideas I was having.

**Comment by nicko88** [comment]
There's a minor bug when saving the settings when the settings file doesn't exist yet.

The save process tries to add the standard fan speed MQTT topics and payloads to the dictionary again (because they were added by the settings default values), but you can't add another same key "OFF" to the dictionary again.

I plan to merge this, and then fix the bug, and then put in my Roku changes and release a beta build for your testing.

**Comment by ndbroadbent** [comment]
Awesome, thanks! I've been testing the changes on my Roku and it feels a lot more accurate than the Plex client app

**Comment by nicko88** [comment]
Another issue that I'd like to avoid is that this change is breaking to current users settings files and I normally really like to avoid that.

What I was originally thinking is that the settings could work as an either/or with the settings storing the MQTT settings as they currently are, and a checkbox like "Advanced MQTT Setup" ( new settings bool field) which when enabled the user would need to manually enter all their topics and payloads into the JSON file manually.

Since my poor web "framework" is not at all built for a dynamic list of settings fields as you have seen.

**Comment by nicko88** [comment]
After thinking longer, I think I will be re-implementing this very similarly in a settings file backwards-compatible way and so I will leave this here for now as a reference and will close it once I have my solution completed.

Since I think you are up and running on your fork for now as well, I am not so pressed for time.

I thank you very much for the inspiration for this extension.

Please let me know here if in the next few days before I have completed my re-implementation if you run into any other features that you may need in this extension for your use.

If not, we can always build on more functionality into this extension later of course.

**Comment by ndbroadbent** [comment]
Thanks, that sounds good about making it backwards compatible!

My fork is running well and meets all my requirements for now so no hurry! I also have another repo on GitHub that I'm using for my own custom wind/effects tracks, including some scripts to detect flashes, compile and sync to my server, etc. https://github.com/ndbroadbent/HTFanControlTracks
I don't know, maybe there's something interesting in there! I might start making some wind tracks and sharing them on the forum as well.

I've also been thinking that it could be nice to have a web-based wind track editor. I run macOS / Windows so I don't know if I can use your wind track creator program. Although I might be able to run it with WINE, or compile it for macOS. I will try that out at some point. For now I'm fine with typing in the timestamps into my text editor.

**Comment by nicko88** [comment]
Yeah, I saw your repo and work on some WindTracks with strobe and smoke, and your opencv script for flashes is awesome.

Unfortunately you won't get WindTrackCreator compiled on anything but Windows as it's written in .NET WinForms which is a Windows only UI system.  It may run in WINE, I have no idea, but I am pretty sure it will likely run into some problems on WINE even if it does run.

A web-based UI wind track creator would be great.  I didn't make one mainly because I am much more well-versed in windows desktop apps rather than web.  I do want to learn .NET Core MVC which is a .NET web server / web ui system though.

However, I have some nice features in the windows WindTrackCreator that I don't think I could easily emulate in a web-based environment.  Such as having the movie file open in the MPC media player, and the MPC media player the focused app, and have global OS hotkeys interact with WindTrackCreator, like adding and inserting commands while you are scrubbing through the movie in the MPC player.

It makes it super easy to scrub through the movie in the lightweight media player, and then simply press hotkeys that insert and manage the commands to the precice millisecond into the wind track file.

I am sure something great could be built though one way or another.


If you make wind tracks through another method, don't worry about the audio fingerprints part.  I don't think anyone out there is using them yet, and I can likely create them for your wind track myself later.

**Comment by nicko88** [comment]
I finally got around to implementing this as I wanted, and appropriately compatible with existing config files etc.

Information on how to use the "Advanced MQTT mode" is written here:

https://www.avsforum.com/threads/4d-theater-wind-effect-diy-home-theater-project.3152346/page-72#post-62415062


Thanks again for the inspiration and code example on an easy and unobtrusive way to add custom MQTT command support.

**Pull request closed without merging**
